#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Feb 27 13:59:11 2011

import wx

# begin wxGlade: extracode
# end wxGlade

import nepaliUnitConverter


class myFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: myFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.volumeTab = wx.Panel(self.notebook_1, -1)
        self.weightTab = wx.Panel(self.notebook_1, -1)
        self.areaTab = wx.Panel(self.notebook_1, -1)
        self.areaText = wx.TextCtrl(self.areaTab, -1, "")
        self.areaComboBox = wx.ComboBox(self.areaTab, -1, choices=["Local To Metric", "Metric To Local"], style=wx.CB_DROPDOWN)
        self.localAreaRadioBox = wx.RadioBox(self.areaTab, -1, "Local Units", choices=["Muri Mato", "Pathi Mato", "Ropani", "Bigha", "Katha", "Anna", "Dhur"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.metricAreaRadioBox = wx.RadioBox(self.areaTab, -1, "Metric Units", choices=["Hectares", "Acres"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.clearAreaButton = wx.Button(self.areaTab, -1, "Clear")
        self.convertAreaButton = wx.Button(self.areaTab, -1, "Convert")
        self.weightText = wx.TextCtrl(self.weightTab, -1, "")
        self.weightComboBox = wx.ComboBox(self.weightTab, -1, choices=["Local To Metric", "Metric To Local"], style=wx.CB_DROPDOWN)
        self.localWeightRadioBox = wx.RadioBox(self.weightTab, -1, "Local Units", choices=["choice 1"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.metricWeightRadioBox = wx.RadioBox(self.weightTab, -1, "Metric Units", choices=["choice 1"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.clearWeightButton = wx.Button(self.weightTab, -1, "Clear")
        self.convertWeightButton = wx.Button(self.weightTab, -1, "Convert")
        self.volumeText = wx.TextCtrl(self.volumeTab, -1, "")
        self.volumeComboBox = wx.ComboBox(self.volumeTab, -1, choices=["Local To Metric", "Metric To Local"], style=wx.CB_DROPDOWN)
        self.localVolumeRadioBox = wx.RadioBox(self.volumeTab, -1, "Local Units", choices=["choice 1"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.metricVolumeRadioRox = wx.RadioBox(self.volumeTab, -1, "Metric Units", choices=["choice 1"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.clearVolumeButton = wx.Button(self.volumeTab, -1, "Clear")
        self.convertVolumeButton = wx.Button(self.volumeTab, -1, "Convert")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onClearAreaButton, self.clearAreaButton)
        self.Bind(wx.EVT_BUTTON, self.onConvertAreaButton, self.convertAreaButton)
        self.Bind(wx.EVT_BUTTON, self.onClearWeightButton, self.clearWeightButton)
        self.Bind(wx.EVT_BUTTON, self.onConvertWeightButton, self.convertWeightButton)
        self.Bind(wx.EVT_BUTTON, self.onClearVolumeButton, self.clearVolumeButton)
        self.Bind(wx.EVT_BUTTON, self.onConvertVolumeButton, self.convertVolumeButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: myFrame.__set_properties
        self.SetTitle("Nepali Units Converter")
        self.areaComboBox.SetSelection(0)
        self.localAreaRadioBox.SetSelection(0)
        self.metricAreaRadioBox.SetSelection(0)
        self.weightComboBox.SetSelection(0)
        self.localWeightRadioBox.SetSelection(0)
        self.metricWeightRadioBox.SetSelection(0)
        self.volumeComboBox.SetSelection(0)
        self.localVolumeRadioBox.SetSelection(0)
        self.metricVolumeRadioRox.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: myFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.areaText, 0, wx.EXPAND, 0)
        sizer_2.Add(self.areaComboBox)
        sizer_3.Add(self.localAreaRadioBox)
        sizer_3.Add(self.metricAreaRadioBox)
        sizer_2.Add(sizer_3)
        sizer_4.Add(self.clearAreaButton)
        sizer_4.Add(self.convertAreaButton)
        sizer_2.Add(sizer_4)
        self.areaTab.SetSizer(sizer_2)
        sizer_5.Add(self.weightText, 0, wx.EXPAND, 0)
        sizer_5.Add(self.weightComboBox)
        sizer_6.Add(self.localWeightRadioBox)
        sizer_6.Add(self.metricWeightRadioBox)
        sizer_5.Add(sizer_6)
        sizer_7.Add(self.clearWeightButton)
        sizer_7.Add(self.convertWeightButton)
        sizer_5.Add(sizer_7)
        self.weightTab.SetSizer(sizer_5)
        sizer_8.Add(self.volumeText, 0, wx.EXPAND, 0)
        sizer_8.Add(self.volumeComboBox)
        sizer_9.Add(self.localVolumeRadioBox)
        sizer_9.Add(self.metricVolumeRadioRox)
        sizer_8.Add(sizer_9)
        sizer_10.Add(self.clearVolumeButton)
        sizer_10.Add(self.convertVolumeButton)
        sizer_8.Add(sizer_10)
        self.volumeTab.SetSizer(sizer_8)
        self.notebook_1.AddPage(self.areaTab, "Area")
        self.notebook_1.AddPage(self.weightTab, "Weight")
        self.notebook_1.AddPage(self.volumeTab, "Volume")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onClearAreaButton(self, event): # wxGlade: myFrame.<event_handler>
        self.areaText.Clear()
    
    def onConvertAreaButton(self, event): # wxGlade: myFrame.<event_handler>
        localUnit = self.localAreaRadioBox.GetString(self.localAreaRadioBox.GetSelection())
        metricUnit = self.metricAreaRadioBox.GetString(self.metricAreaRadioBox.GetSelection())
        toConvertValue = float(self.areaText.GetValue())
        fromTo = self.areaComboBox.GetString(self.areaComboBox.GetSelection())
        currentUnits = self.notebook_1.GetPageText(self.notebook_1.GetSelection())
        returnData = nepaliUnitConverter.convert(currentUnits, fromTo, localUnit, metricUnit, toConvertValue)
        self.areaText.Clear()
        self.areaText.SetValue(str(returnData))
        
    def onClearWeightButton(self, event): # wxGlade: myFrame.<event_handler>
        self.weightText.Clear()

    def onConvertWeightButton(self, event): # wxGlade: myFrame.<event_handler>
        localUnit = self.localWeightRadioBox.GetString(self.localWeightRadioBox.GetSelection())
        metricUnit = self.metricWeightRadioBox.GetString(self.metricWeightRadioBox.GetSelection())
        toConvertValue = self.weightText.GetValue()
        fromTo = self.weightComboBox.GetString(self.weightComboBox.GetSelection())
        currentUnits = self.notebook_1.GetPageText(self.notebook_1.GetSelection())
        returnData = nepaliUnitConverter.convert(currentUnits, fromTo, localUnit, metricUnit, toConvertValue)

    def onClearVolumeButton(self, event): # wxGlade: myFrame.<event_handler>
        self.volumeText.Clear()

    def onConvertVolumeButton(self, event): # wxGlade: myFrame.<event_handler>
        localUnit = self.localVolumeRadioBox.GetString(self.localVolumeRadioBox.GetSelection())
        metricUnit = self.metricVolumeRadioBox.GetString(self.metricVolumeRadioBox.GetSelection())
        toConvertValue = self.volumeText.GetValue()
        fromTo = self.volumeComboBox.GetString(self.volumeComboBox.GetSelection())
        currentUnits = self.notebook_1.GetPageText(self.notebook_1.GetSelection())
        returnData = nepaliUnitConverter.convert(currentUnits, fromTo, localUnit, metricUnit, toConvertValue)

# end of class myFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = myFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
